import { Noto_Sans_TC } from "next/font/google";
import "./globals.css";

const notoSansTC = Noto_Sans_TC({ subsets: ["latin"] });

export const metadata = {
  title: "campaign website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansTC.className} h-screen bg-brand`}>
        {children}
      </body>
    </html>
  );
}
